require "equipment/base"

require "equipment/extra_hand_weapon"
require "equipment/halberd"
require "equipment/murderous_prowess"
require "equipment/poison_attacks"
require "equipment/reroll_misses"
require "equipment/reroll_wounds"
require "equipment/spear"
require "equipment/standard"
require "equipment/sword_of_striking"
require "equipment/random_attacks"
require "equipment/daemonic"
require "equipment/minus_to_hit"
require "equipment/fear"
require "equipment/frenzy"
require "equipment/stomp_attack"
