#!/usr/bin/env zsh

set -e

function run_rbenv {
    rbenv shell 2>&1 > /dev/null
}
if ! run_rbenv ; then
    eval "$(rbenv init -)"
fi

if [ -n "$1" ]; then
    #rspec --color "$1"
    ruby -Ispec "$1"
else
    #rspec --color --format progress --require "~/lib/vim_rspec_formatter" --format VimFormatter spec
    rake test
fi

